# Generated by Django 6.1.1 on 2026-09-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='status',
            field=models.CharField(choices=[('acompanho', 'Acompanho'), ('nao_acompanho', 'Não acompanho')], default='acompanho', max_length=20),
        ),
    ]
